name: Deploy to Server

on:
  push:
    branches:
      - main  # Adjust based on your deployment branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up SSH
      id: setup_ssh
      run: |
        # Create SSH directory
        mkdir -p ~/.ssh
        
        # Add the SSH private key from the GitHub Secrets
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        
        # Add the SSH config file from GitHub Secrets
        echo "${{ secrets.SSH_CONFIG }}" > ~/.ssh/config
        chmod 600 ~/.ssh/config
        
        # Install sshpass to handle passphrase
        sudo apt-get update && sudo apt-get install -y sshpass
        
        # Start SSH agent
        eval "$(ssh-agent -s)"
        
        # Add server to known hosts to prevent prompt issues
        ssh-keyscan -H bazooka.cs.ait.ac.th >> ~/.ssh/known_hosts
        ssh-keyscan -H ml.brain.cs.ait.ac.th >> ~/.ssh/known_hosts

    - name: Test SSH Connection Using sshpass
      run: |
        # Use sshpass to supply the passphrase automatically
        sshpass -p "${{ secrets.SSH_PASSPHRASE }}" ssh -o StrictHostKeyChecking=no ml-brain "echo 'Connected Successfully via Proxy Jump'"
