name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: bazooka.cs.ait.ac.th
          username: st125462
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          passphrase: ${{ secrets.BAZOOKA_PASSWORD }}
          port: 22
          script: whoami
