name: Deploy to Server

on:
  push:
    branches:
      - main  # Adjust this to match your deployment branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up SSH with Debug Output
      id: setup_ssh
      run: |
        set -x  # Enable debugging output to trace commands
        
        # Create SSH directory
        mkdir -p ~/.ssh
        
        # Add the SSH private key from GitHub Secrets
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        
        # Add the SSH config file from GitHub Secrets
        echo "${{ secrets.SSH_CONFIG }}" > ~/.ssh/config
        chmod 600 ~/.ssh/config
        
        # Install sshpass to handle the password and passphrase prompts
        sudo apt-get update && sudo apt-get install -y sshpass
        
        # Add server host keys to known hosts to avoid manual prompts
        ssh-keyscan -H bazooka.cs.ait.ac.th >> ~/.ssh/known_hosts
        ssh-keyscan -H ml.brain.cs.ait.ac.th >> ~/.ssh/known_hosts

    - name: Connect to ml-brain via Proxy Jump with Debug Output
      run: |
        set -x  # Enable debugging output
        
        # Combine both passphrase handling for SSH key and proxy jump password in one command
        export SSHPASS="${{ secrets.BAZOOKA_PASSWORD }}"
        export SSH_ASKPASS=/usr/bin/sshpass  # Direct SSH to use sshpass
        
        # Test SSH connection with detailed logging
        sshpass -e ssh -o "IdentitiesOnly=yes" -o "IdentityFile=~/.ssh/id_rsa" -o "StrictHostKeyChecking=no" -J bazooka ml-brain \
          "echo 'Connected Successfully via Proxy Jump'"
