name: SSH to Remote Server

on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install sshpass
        run: sudo apt-get install sshpass

      - name: Setup SSH key
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H bazooka.cs.ait.ac.th >> ~/.ssh/known_hosts
          ssh-keyscan -H ml.brain.cs.ait.ac.th >> ~/.ssh/known_hosts

      - name: Connect to remote server
        env:
          JUMP_PASSWORD: ${{ secrets.BAZOOKA_PASSWORD }}
          KEY_PASSPHRASE: ${{ secrets.SSH_PASSPHRASE }}
        run: |
          sshpass -p "$JUMP_PASSWORD" ssh -o ProxyCommand="sshpass -p $JUMP_PASSWORD ssh -W %h:%p st125462@bazooka.cs.ait.ac.th" st125462@ml.brain.cs.ait.ac.th << EOF
            echo "Connected Successfully via Proxy Jump"
            # Add your commands here
          EOF

      - name: Debug SSH connection
        if: failure()
        env:
          JUMP_PASSWORD: ${{ secrets.JUMP_PASSWORD }}
          KEY_PASSPHRASE: ${{ secrets.KEY_PASSPHRASE }}
        run: |
          sshpass -p "$JUMP_PASSWORD" ssh -vvv -o ProxyCommand="sshpass -p $JUMP_PASSWORD ssh -W %h:%p st125462@bazooka.cs.ait.ac.th" st125462@ml.brain.cs.ait.ac.th
